name: codeinsights

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  provider: ^6.1.1
  english_words: ^4.0.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: TeXGyreBonum
      fonts:
        - asset: fonts/texgyrebonum.ttf

environment:
  sdk: '>=2.12.0 <3.0.0'
